name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r . -f html -o bandit-report.html
        continue-on-error: true

      - name: Upload Bandit Report to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
          aws s3 cp bandit-report.html s3://dev-py-s3/bandit_report/bandit-report.html --region ap-southeast-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-flask:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-flask:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: |
          'docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world-flask:latest && docker run -d -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/hello-world-flask:latest'
